Projectile = "repairshot" --shoots the healing projectile
ReloadTime = 1
MinFireSpeed = MinFireSpeed/2 --speed when aimed at the lowest %
MaxFireSpeed = MaxFireSpeed/2 --speed when aimed at the highest %
MinFireRadius = 200.0
MaxFireRadius = 500.0
MinFireAngle = 60 --bottom angle (right)
MaxFireAngle = 120 --top angle (left)
IgnorePlatformSlope = true --makes it so the angle of the weapon doesn't change the fire angle (standart mortar code)
EnergyFireCost = 100
MetalFireCost = 50